CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,
	title VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS GenreArtist (
	id SERIAL PRIMARY KEY,
	artist_id INTEGER NOT NULL REFERENCES Artist(id),
	genre_id INTEGER NOT NULL REFERENCES Genre(id)
);

CREATE TABLE IF NOT EXISTS Artist (
	id SERIAL PRIMARY KEY,
	nickname VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS HomeworkTask (
	id SERIAL PRIMARY KEY,
	artist_id INTEGER NOT NULL REFERENCES Artist(id),
	alb_id INTEGER NOT NULL REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	title VARCHAR(40) NOT NULL,
	year INTEGER NOT NULL	
);

CREATE TABLE IF NOT EXISTS Collection (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) not null,
	year INTEGER not null
);

CREATE TABLE IF NOT EXISTS CollectionTrack (
	collection_id INTEGER NOT NULL REFERENCES Collection(id),
	track_id INTEGER NOT NULL REFERENCES Track(id),
	CONSTRAINT pk PRIMARY KEY (collection_id, track_id)
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	duration VARCHAR(40) NOT NULL,
	album_id INTEGER NOT NULL REFERENCES Album(id)
);